---
abstract: "Generate and validate 'CouponCode' strings"
author:
  - 'Grant McLean <grantm@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-CouponCode
requires:
  Digest::SHA1: 2.13
  perl: 5.010
version: 1.000
