---
abstract: "Generate and validate 'CouponCode' strings"
author:
  - 'Grant McLean <grantm@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-CouponCode
requires:
  Digest::SHA: 0
  perl: 5.010
resources:
  repository: git://github.com/grantm/Algorithm-CouponCode.git
version: 1.004
